const allColleges = [
  {
    id: 1,
    name: "Harvard University",
    image: "/placeholder.svg?height=300&width=400",
    rating: 4.9,
    admissionDate: "December 2024",
    researchCount: 150,
    events: ["Tech Fest", "Cultural Night"],
    sports: ["Basketball", "Soccer"],
    description:
      "World-renowned university known for excellence in education and research.",
    location: "Cambridge, Massachusetts, USA",
    established: "1636",
    type: "Private University",
    website: "https://www.harvard.edu",
    phone: "+1-617-495-1000",
    email: "info@harvard.edu",
    admissionProcess: {
      requirements: [
        "SAT/ACT scores",
        "High school GPA 3.8+",
        "Letters of recommendation",
        "Personal essay",
        "Interview (optional)",
      ],
      deadlines: {
        earlyAction: "November 1, 2024",
        regularDecision: "January 1, 2025",
        financialAid: "February 1, 2025",
      },
      tuition: "$54,000 per year",
      acceptanceRate: "4.5%",
    },
    events: [
      {
        name: "Harvard Tech Fest",
        date: "October 10-12, 2024",
        description: "Showcase of cutting-edge technology and innovation",
        category: "Technology",
      },
    ],
    research: [
      {
        title: "AI in Healthcare",
        department: "Computer Science",
        funding: "$5M",
        description: "Developing AI-driven diagnostic tools",
      },
    ],
    sports: [
      {
        name: "Basketball",
        level: "NCAA Division I",
        achievements: ["Ivy League Champion 2023"],
        facilities: "Lavietes Pavilion",
      },
    ],
    facilities: [
      "Advanced research labs",
      "Widener Library",
      "Sports complex",
      "Student dormitories",
      "Dining halls",
    ],
    stats: {
      students: "20,000+",
      faculty: "2,400+",
      programs: "50+",
      campusSize: "209 acres",
    },
  },
  {
    id: 2,
    name: "MIT",
    image: "/placeholder.svg?height=300&width=400",
    rating: 4.8,
    admissionDate: "January 2025",
    researchCount: 200,
    events: ["Innovation Summit", "Robotics Fair"],
    sports: ["Tennis", "Swimming"],
    description: "Leading institution in technology and engineering education.",
    location: "Cambridge, Massachusetts, USA",
    established: "1861",
    type: "Private University",
    website: "https://www.mit.edu",
    phone: "+1-617-253-1000",
    email: "admissions@mit.edu",
    admissionProcess: {
      requirements: [
        "SAT/ACT scores",
        "High school GPA 3.9+",
        "Two teacher recommendations",
        "Personal essays",
        "STEM project portfolio",
      ],
      deadlines: {
        earlyAction: "November 1, 2024",
        regularDecision: "January 5, 2025",
        financialAid: "February 15, 2025",
      },
      tuition: "$57,000 per year",
      acceptanceRate: "6.7%",
    },
    events: [
      {
        name: "MIT Innovation Summit",
        date: "September 15-17, 2024",
        description: "Platform for startups and tech innovators",
        category: "Entrepreneurship",
      },
    ],
    research: [
      {
        title: "Quantum Computing",
        department: "Physics",
        funding: "$10M",
        description: "Advancing quantum algorithms for computing",
      },
    ],
    sports: [
      {
        name: "Tennis",
        level: "NCAA Division III",
        achievements: ["NEWMAC Champions 2022"],
        facilities: "J.B. Carr Tennis Bubble",
      },
    ],
    facilities: [
      "MIT Media Lab",
      "Nuclear reactor",
      "Sports facilities",
      "Libraries",
      "Innovation hubs",
    ],
    stats: {
      students: "11,500+",
      faculty: "1,000+",
      programs: "40+",
      campusSize: "168 acres",
    },
  },
  {
    id: 3,
    name: "Stanford University",
    image: "/placeholder.svg?height=300&width=400",
    rating: 4.9,
    admissionDate: "February 2025",
    researchCount: 180,
    events: ["Startup Expo", "AI Conference"],
    sports: ["Football", "Baseball"],
    description:
      "Premier university fostering innovation and entrepreneurship.",
    location: "Stanford, California, USA",
    established: "1885",
    type: "Private University",
    website: "https://www.stanford.edu",
    phone: "+1-650-723-2300",
    email: "admission@stanford.edu",
    admissionProcess: {
      requirements: [
        "SAT/ACT scores",
        "High school GPA 3.9+",
        "Three recommendation letters",
        "Personal statement",
        "Extracurricular achievements",
      ],
      deadlines: {
        earlyAction: "November 1, 2024",
        regularDecision: "January 2, 2025",
        financialAid: "February 15, 2025",
      },
      tuition: "$56,000 per year",
      acceptanceRate: "4.3%",
    },
    events: [
      {
        name: "Stanford Startup Expo",
        date: "March 10-12, 2025",
        description: "Showcasing student-led startups",
        category: "Entrepreneurship",
      },
    ],
    research: [
      {
        title: "Sustainable Energy Solutions",
        department: "Engineering",
        funding: "$8M",
        description: "Research on renewable energy technologies",
      },
    ],
    sports: [
      {
        name: "Football",
        level: "NCAA Division I",
        achievements: ["Pac-12 Champions 2021"],
        facilities: "Stanford Stadium",
      },
    ],
    facilities: [
      "Research labs",
      "Hoover Tower",
      "Sports complex",
      "Student housing",
      "Dining facilities",
    ],
    stats: {
      students: "16,000+",
      faculty: "2,200+",
      programs: "65+",
      campusSize: "8,180 acres",
    },
  },
  {
    id: 4,
    name: "Yale University",
    image: "/placeholder.svg?height=300&width=400",
    rating: 4.7,
    admissionDate: "March 2025",
    researchCount: 120,
    events: ["Drama Festival", "Music Concert"],
    sports: ["Rowing", "Hockey"],
    description: "Historic university with strong liberal arts programs.",
    location: "New Haven, Connecticut, USA",
    established: "1701",
    type: "Private University",
    website: "https://www.yale.edu",
    phone: "+1-203-432-4771",
    email: "admissions@yale.edu",
    admissionProcess: {
      requirements: [
        "SAT/ACT scores",
        "High school GPA 3.8+",
        "Two teacher recommendations",
        "Personal essay",
        "Interview (optional)",
      ],
      deadlines: {
        earlyAction: "November 1, 2024",
        regularDecision: "January 2, 2025",
        financialAid: "March 1, 2025",
      },
      tuition: "$59,000 per year",
      acceptanceRate: "5.9%",
    },
    events: [
      {
        name: "Yale Drama Festival",
        date: "April 5-7, 2025",
        description: "Showcase of student theater productions",
        category: "Arts",
      },
    ],
    research: [
      {
        title: "Climate Change Policy",
        department: "Environmental Studies",
        funding: "$3M",
        description: "Policy frameworks for sustainable development",
      },
    ],
    sports: [
      {
        name: "Rowing",
        level: "NCAA Division I",
        achievements: ["Ivy League Rowing Champions 2022"],
        facilities: "Gilder Boathouse",
      },
    ],
    facilities: [
      "Yale Art Gallery",
      "Libraries",
      "Sports facilities",
      "Residential colleges",
      "Theater spaces",
    ],
    stats: {
      students: "12,000+",
      faculty: "1,500+",
      programs: "80+",
      campusSize: "345 acres",
    },
  },
  {
    id: 5,
    name: "Princeton University",
    image: "/placeholder.svg?height=300&width=400",
    rating: 4.8,
    admissionDate: "April 2025",
    researchCount: 140,
    events: ["Science Fair", "Art Exhibition"],
    sports: ["Lacrosse", "Golf"],
    description: "Elite institution known for undergraduate education.",
    location: "Princeton, New Jersey, USA",
    established: "1746",
    type: "Private University",
    website: "https://www.princeton.edu",
    phone: "+1-609-258-3000",
    email: "uaoffice@princeton.edu",
    admissionProcess: {
      requirements: [
        "SAT/ACT scores",
        "High school GPA 3.9+",
        "Three recommendation letters",
        "Personal essay",
        "Graded written paper",
      ],
      deadlines: {
        earlyAction: "November 1, 2024",
        regularDecision: "January 1, 2025",
        financialAid: "February 1, 2025",
      },
      tuition: "$57,000 per year",
      acceptanceRate: "5.8%",
    },
    events: [
      {
        name: "Princeton Science Fair",
        date: "March 15-16, 2025",
        description: "Student-led scientific research presentations",
        category: "Science",
      },
    ],
    research: [
      {
        title: "Astrophysics Research",
        department: "Physics",
        funding: "$4M",
        description: "Study of exoplanets and cosmology",
      },
    ],
    sports: [
      {
        name: "Lacrosse",
        level: "NCAA Division I",
        achievements: ["Ivy League Champions 2023"],
        facilities: "Class of 1952 Stadium",
      },
    ],
    facilities: [
      "Research labs",
      "Firestone Library",
      "Sports facilities",
      "Residential colleges",
      "Art museum",
    ],
    stats: {
      students: "8,500+",
      faculty: "1,200+",
      programs: "50+",
      campusSize: "600 acres",
    },
  },
  {
    id: 6,
    name: "Columbia University",
    image: "/placeholder.svg?height=300&width=400",
    rating: 4.6,
    admissionDate: "May 2025",
    researchCount: 160,
    events: ["Journalism Workshop", "Business Summit"],
    sports: ["Track", "Volleyball"],
    description: "Urban university with strong professional programs.",
    location: "New York City, New York, USA",
    established: "1754",
    type: "Private University",
    website: "https://www.columbia.edu",
    phone: "+1-212-854-1754",
    email: "admissions@columbia.edu",
    admissionProcess: {
      requirements: [
        "SAT/ACT scores",
        "High school GPA 3.8+",
        "Two teacher recommendations",
        "Personal essays",
        "Extracurricular profile",
      ],
      deadlines: {
        earlyAction: "November 1, 2024",
        regularDecision: "January 1, 2025",
        financialAid: "March 1, 2025",
      },
      tuition: "$61,000 per year",
      acceptanceRate: "5.1%",
    },
    events: [
      {
        name: "Columbia Journalism Workshop",
        date: "February 20-22, 2025",
        description: "Training for aspiring journalists",
        category: "Journalism",
      },
    ],
    research: [
      {
        title: "Urban Planning Studies",
        department: "Architecture",
        funding: "$2.5M",
        description: "Sustainable urban development research",
      },
    ],
    sports: [
      {
        name: "Track",
        level: "NCAA Division I",
        achievements: ["Ivy League Track Champions 2022"],
        facilities: "Robert K. Kraft Field",
      },
    ],
    facilities: [
      "Butler Library",
      "Research centers",
      "Sports facilities",
      "Student housing",
      "Medical center",
    ],
    stats: {
      students: "31,000+",
      faculty: "4,000+",
      programs: "100+",
      campusSize: "36 acres",
    },
  },
  {
    id: 7,
    name: "University of Chicago",
    image: "/placeholder.svg?height=300&width=400",
    rating: 4.7,
    admissionDate: "June 2025",
    researchCount: 130,
    events: ["Economics Forum", "Philosophy Debate"],
    sports: ["Wrestling", "Cross Country"],
    description: "Renowned for rigorous academics and intellectual discourse.",
    location: "Chicago, Illinois, USA",
    established: "1890",
    type: "Private University",
    website: "https://www.uchicago.edu",
    phone: "+1-773-702-1234",
    email: "admissions@uchicago.edu",
    admissionProcess: {
      requirements: [
        "SAT/ACT scores (optional)",
        "High school GPA 3.8+",
        "Two recommendation letters",
        "Creative essays",
        "Extracurricular achievements",
      ],
      deadlines: {
        earlyAction: "November 1, 2024",
        regularDecision: "January 2, 2025",
        financialAid: "February 15, 2025",
      },
      tuition: "$60,000 per year",
      acceptanceRate: "6.2%",
    },
    events: [
      {
        name: "UChicago Economics Forum",
        date: "April 10-12, 2025",
        description: "Discussion on global economic trends",
        category: "Economics",
      },
    ],
    research: [
      {
        title: "Behavioral Economics",
        department: "Economics",
        funding: "$3M",
        description: "Studying decision-making processes",
      },
    ],
    sports: [
      {
        name: "Wrestling",
        level: "NCAA Division III",
        achievements: ["UAA Champions 2023"],
        facilities: "Ratner Athletics Center",
      },
    ],
    facilities: [
      "Research institutes",
      "Regenstein Library",
      "Sports facilities",
      "Student housing",
      "Cultural centers",
    ],
    stats: {
      students: "17,000+",
      faculty: "2,300+",
      programs: "50+",
      campusSize: "217 acres",
    },
  },
  {
    id: 8,
    name: "California Institute of Technology",
    image: "/placeholder.svg?height=300&width=400",
    rating: 4.8,
    admissionDate: "July 2025",
    researchCount: 190,
    events: ["Space Exploration Symposium", "Robotics Competition"],
    sports: ["Water Polo", "Fencing"],
    description: "Leading institution in science and engineering research.",
    location: "Pasadena, California, USA",
    established: "1891",
    type: "Private University",
    website: "https://www.caltech.edu",
    phone: "+1-626-395-6811",
    email: "admissions@caltech.edu",
    admissionProcess: {
      requirements: [
        "SAT/ACT scores",
        "High school GPA 3.9+",
        "Three recommendation letters",
        "STEM-focused essays",
        "Research experience",
      ],
      deadlines: {
        earlyAction: "November 1, 2024",
        regularDecision: "January 3, 2025",
        financialAid: "February 15, 2025",
      },
      tuition: "$58,000 per year",
      acceptanceRate: "6.4%",
    },
    events: [
      {
        name: "Caltech Space Symposium",
        date: "May 5-7, 2025",
        description: "Exploration of space technologies",
        category: "Science",
      },
    ],
    research: [
      {
        title: "Exoplanet Research",
        department: "Astronomy",
        funding: "$12M",
        description: "Discovering habitable exoplanets",
      },
    ],
    sports: [
      {
        name: "Water Polo",
        level: "NCAA Division III",
        achievements: ["SCIAC Champions 2022"],
        facilities: "Braun Aquatic Center",
      },
    ],
    facilities: [
      "Jet Propulsion Laboratory",
      "Research labs",
      "Sports facilities",
      "Student housing",
      "Libraries",
    ],
    stats: {
      students: "2,200+",
      faculty: "300+",
      programs: "25+",
      campusSize: "124 acres",
    },
  },
  {
    id: 9,
    name: "University of Pennsylvania",
    image: "/placeholder.svg?height=300&width=400",
    rating: 4.6,
    admissionDate: "August 2025",
    researchCount: 145,
    events: ["Business Case Competition", "Medical Research Showcase"],
    sports: ["Crew", "Squash"],
    description:
      "Ivy League university with strong business and medical programs.",
    location: "Philadelphia, Pennsylvania, USA",
    established: "1740",
    type: "Private University",
    website: "https://www.upenn.edu",
    phone: "+1-215-898-5000",
    email: "info@admissions.upenn.edu",
    admissionProcess: {
      requirements: [
        "SAT/ACT scores",
        "High school GPA 3.8+",
        "Two recommendation letters",
        "Personal essay",
        "Extracurricular leadership",
      ],
      deadlines: {
        earlyAction: "November 1, 2024",
        regularDecision: "January 5, 2025",
        financialAid: "February 1, 2025",
      },
      tuition: "$60,000 per year",
      acceptanceRate: "7.4%",
    },
    events: [
      {
        name: "Wharton Business Case Competition",
        date: "March 20-22, 2025",
        description: "Competition for business students",
        category: "Business",
      },
    ],
    research: [
      {
        title: "Biomedical Engineering",
        department: "Engineering",
        funding: "$4.5M",
        description: "Innovations in medical devices",
      },
    ],
    sports: [
      {
        name: "Crew",
        level: "NCAA Division I",
        achievements: ["Ivy League Champions 2023"],
        facilities: "Penn Boathouse",
      },
    ],
    facilities: [
      "Wharton School",
      "Research labs",
      "Sports facilities",
      "Libraries",
      "Student housing",
    ],
    stats: {
      students: "22,000+",
      faculty: "4,700+",
      programs: "90+",
      campusSize: "299 acres",
    },
  },
  {
    id: 10,
    name: "Duke University",
    image: "/placeholder.svg?height=300&width=400",
    rating: 4.7,
    admissionDate: "September 2025",
    researchCount: 135,
    events: ["Global Health Summit", "Arts Festival"],
    sports: ["Basketball", "Lacrosse"],
    description: "Premier research university with beautiful campus.",
    location: "Durham, North Carolina, USA",
    established: "1838",
    type: "Private University",
    website: "https://www.duke.edu",
    phone: "+1-919-684-8111",
    email: "undergrad-admissions@duke.edu",
    admissionProcess: {
      requirements: [
        "SAT/ACT scores",
        "High school GPA 3.9+",
        "Two recommendation letters",
        "Personal essays",
        "Extracurricular achievements",
      ],
      deadlines: {
        earlyAction: "November 1, 2024",
        regularDecision: "January 2, 2025",
        financialAid: "February 1, 2025",
      },
      tuition: "$58,000 per year",
      acceptanceRate: "7.8%",
    },
    events: [
      {
        name: "Duke Global Health Summit",
        date: "April 15-17, 2025",
        description: "Addressing global health challenges",
        category: "Health",
      },
    ],
    research: [
      {
        title: "Global Health Innovations",
        department: "Medicine",
        funding: "$6M",
        description: "Solutions for global health issues",
      },
    ],
    sports: [
      {
        name: "Basketball",
        level: "NCAA Division I",
        achievements: ["ACC Champions 2023"],
        facilities: "Cameron Indoor Stadium",
      },
    ],
    facilities: [
      "Duke Hospital",
      "Research labs",
      "Sports facilities",
      "Gothic-style campus",
      "Libraries",
    ],
    stats: {
      students: "16,000+",
      faculty: "3,800+",
      programs: "50+",
      campusSize: "8,600 acres",
    },
  },
  {
    id: 11,
    name: "Northwestern University",
    image: "/placeholder.svg?height=300&width=400",
    rating: 4.5,
    admissionDate: "October 2025",
    researchCount: 125,
    events: ["Journalism Conference", "Theater Showcase"],
    sports: ["Football", "Sailing"],
    description:
      "Top-tier university known for journalism and performing arts.",
    location: "Evanston, Illinois, USA",
    established: "1851",
    type: "Private University",
    website: "https://www.northwestern.edu",
    phone: "+1-847-491-3741",
    email: "ug-admission@northwestern.edu",
    admissionProcess: {
      requirements: [
        "SAT/ACT scores",
        "High school GPA 3.8+",
        "Two recommendation letters",
        "Personal essay",
        "Extracurricular profile",
      ],
      deadlines: {
        earlyAction: "November 1, 2024",
        regularDecision: "January 3, 2025",
        financialAid: "February 15, 2025",
      },
      tuition: "$60,000 per year",
      acceptanceRate: "7.2%",
    },
    events: [
      {
        name: "Medill Journalism Conference",
        date: "March 10-12, 2025",
        description: "Networking for journalism students",
        category: "Journalism",
      },
    ],
    research: [
      {
        title: "Media Studies",
        department: "Communication",
        funding: "$2M",
        description: "Impact of digital media on society",
      },
    ],
    sports: [
      {
        name: "Football",
        level: "NCAA Division I",
        achievements: ["Big Ten Champions 2020"],
        facilities: "Ryan Field",
      },
    ],
    facilities: [
      "Medill School of Journalism",
      "Research centers",
      "Sports facilities",
      "Theater spaces",
      "Libraries",
    ],
    stats: {
      students: "21,000+",
      faculty: "3,400+",
      programs: "70+",
      campusSize: "240 acres",
    },
  },
  {
    id: 12,
    name: "Johns Hopkins University",
    image: "/placeholder.svg?height=300&width=400",
    rating: 4.8,
    admissionDate: "November 2025",
    researchCount: 175,
    events: ["Medical Innovation Summit", "Public Health Forum"],
    sports: ["Lacrosse", "Soccer"],
    description: "World leader in medical research and education.",
    location: "Baltimore, Maryland, USA",
    established: "1876",
    type: "Private University",
    website: "https://www.jhu.edu",
    phone: "+1-410-516-8000",
    email: "admissions@jhu.edu",
    admissionProcess: {
      requirements: [
        "SAT/ACT scores",
        "High school GPA 3.9+",
        "Two recommendation letters",
        "Personal essay",
        "Research experience",
      ],
      deadlines: {
        earlyAction: "November 1, 2024",
        regularDecision: "January 2, 2025",
        financialAid: "February 15, 2025",
      },
      tuition: "$57,000 per year",
      acceptanceRate: "7.5%",
    },
    events: [
      {
        name: "JHU Medical Innovation Summit",
        date: "April 20-22, 2025",
        description: "Showcasing medical breakthroughs",
        category: "Medicine",
      },
    ],
    research: [
      {
        title: "Cancer Research",
        department: "Medicine",
        funding: "$10M",
        description: "Developing new cancer therapies",
      },
    ],
    sports: [
      {
        name: "Lacrosse",
        level: "NCAA Division I",
        achievements: ["Big Ten Champions 2023"],
        facilities: "Homewood Field",
      },
    ],
    facilities: [
      "Johns Hopkins Hospital",
      "Research labs",
      "Sports facilities",
      "Libraries",
      "Student housing",
    ],
    stats: {
      students: "24,000+",
      faculty: "4,500+",
      programs: "50+",
      campusSize: "140 acres",
    },
  },
  {
    id: 13,
    name: "University of Oxford",
    image: "/placeholder.svg?height=300&width=400",
    rating: 4.9,
    admissionDate: "October 2025",
    researchCount: 200,
    events: ["Literary Festival", "Science Symposium"],
    sports: ["Rowing", "Cricket"],
    description:
      "One of the oldest universities, renowned for academic excellence.",
    location: "Oxford, England, UK",
    established: "1096",
    type: "Public University",
    website: "https://www.ox.ac.uk",
    phone: "+44-1865-270000",
    email: "admissions@ox.ac.uk",
    admissionProcess: {
      requirements: [
        "A-levels or equivalent",
        "High school GPA equivalent 3.8+",
        "Admission tests (e.g., LNAT, BMAT)",
        "Personal statement",
        "Interview",
      ],
      deadlines: {
        earlyAction: "October 15, 2024",
        regularDecision: "January 15, 2025",
        financialAid: "March 1, 2025",
      },
      tuition: "£9,250-£36,000 per year",
      acceptanceRate: "17.5%",
    },
    events: [
      {
        name: "Oxford Literary Festival",
        date: "March 25-30, 2025",
        description: "Celebrating literature and ideas",
        category: "Literature",
      },
    ],
    research: [
      {
        title: "Vaccine Development",
        department: "Medicine",
        funding: "£15M",
        description: "Research on infectious diseases",
      },
    ],
    sports: [
      {
        name: "Rowing",
        level: "Intercollegiate",
        achievements: ["Boat Race Winners 2023"],
        facilities: "Oxford University Boat Club",
      },
    ],
    facilities: [
      "Bodleian Library",
      "Research labs",
      "Sports facilities",
      "Colleges",
      "Museums",
    ],
    stats: {
      students: "24,000+",
      faculty: "6,700+",
      programs: "350+",
      campusSize: "City-based",
    },
  },
  {
    id: 14,
    name: "University of Cambridge",
    image: "/placeholder.svg?height=300&width=400",
    rating: 4.9,
    admissionDate: "October 2025",
    researchCount: 190,
    events: ["Science Festival", "Debating Championship"],
    sports: ["Rowing", "Rugby"],
    description: "World-class university with a rich academic tradition.",
    location: "Cambridge, England, UK",
    established: "1209",
    type: "Public University",
    website: "https://www.cam.ac.uk",
    phone: "+44-1223-337733",
    email: "admissions@cam.ac.uk",
    admissionProcess: {
      requirements: [
        "A-levels or equivalent",
        "High school GPA equivalent 3.8+",
        "Admission tests",
        "Personal statement",
        "Interview",
      ],
      deadlines: {
        earlyAction: "October 15, 2024",
        regularDecision: "January 15, 2025",
        financialAid: "March 1, 2025",
      },
      tuition: "£9,250-£33,000 per year",
      acceptanceRate: "21%",
    },
    events: [
      {
        name: "Cambridge Science Festival",
        date: "March 10-16, 2025",
        description: "Public engagement with science",
        category: "Science",
      },
    ],
    research: [
      {
        title: "AI and Machine Learning",
        department: "Computer Science",
        funding: "£10M",
        description: "Advancing AI applications",
      },
    ],
    sports: [
      {
        name: "Rowing",
        level: "Intercollegiate",
        achievements: ["Boat Race Winners 2022"],
        facilities: "Cambridge University Boat Club",
      },
    ],
    facilities: [
      "University Library",
      "Research labs",
      "Sports facilities",
      "Colleges",
      "Museums",
    ],
    stats: {
      students: "23,000+",
      faculty: "5,800+",
      programs: "300+",
      campusSize: "City-based",
    },
  },
  {
    id: 15,
    name: "ETH Zurich",
    image: "/placeholder.svg?height=300&width=400",
    rating: 4.8,
    admissionDate: "September 2025",
    researchCount: 180,
    events: ["Robotics Expo", "Sustainability Summit"],
    sports: ["Skiing", "Soccer"],
    description: "Leading European university in science and technology.",
    location: "Zurich, Switzerland",
    established: "1855",
    type: "Public University",
    website: "https://ethz.ch",
    phone: "+41-44-632-11-11",
    email: "admissions@ethz.ch",
    admissionProcess: {
      requirements: [
        "Matura or equivalent",
        "Entrance exam",
        "High school GPA equivalent 3.8+",
        "Language proficiency",
        "Recommendation letters",
      ],
      deadlines: {
        earlyAction: "April 30, 2025",
        regularDecision: "July 15, 2025",
        financialAid: "June 1, 2025",
      },
      tuition: "CHF 1,460 per year",
      acceptanceRate: "27%",
    },
    events: [
      {
        name: "ETH Robotics Expo",
        date: "June 10-12, 2025",
        description: "Showcasing robotics innovations",
        category: "Technology",
      },
    ],
    research: [
      {
        title: "Sustainable Engineering",
        department: "Engineering",
        funding: "CHF 8M",
        description: "Eco-friendly engineering solutions",
      },
    ],
    sports: [
      {
        name: "Skiing",
        level: "Intercollegiate",
        achievements: ["Swiss University Championships 2023"],
        facilities: "ETH Sports Center",
      },
    ],
    facilities: [
      "Research labs",
      "ETH Library",
      "Sports facilities",
      "Student housing",
      "Innovation hubs",
    ],
    stats: {
      students: "22,000+",
      faculty: "2,500+",
      programs: "40+",
      campusSize: "City-based",
    },
  },
];

const getAllColleges = () => {
  return allColleges;
};

export default getAllColleges;
